### ISSUE TITLE
Farmer's Delight recipe conflict

### ISSUE THREAD

**Issue by 444945** [khazoda/basicweapons-legacy#19]
Hello, after playing with my friends I would like to say that we are loving this mod, it adds a lot of value to combat. However, I've encountered an issue with a crafting conflict involving Farmer's Delight knives, this can be fixed by installing some mods that allow swapping the item output in crafting table, however for a vanilla themed modpack that workaround doesn't seem quite right, Would it be possible to adjust the recipe for daggers (I'd suggest the materials in a diagonal pattern) to avoid this? Thank you.

**Comment by khazoda** [comment]
This is a problem that keeps getting reported to me, and I would like to find a good solution. The trouble with making the dagger's crafting recipe to be diagonal is the following:
## One handed weapons (Dagger, Club, Hammer)
![image](https://github.com/Khazoda/basic-weapons/assets/42558699/2c500322-e21f-4f96-ba92-538e22987ffd)![image](https://github.com/Khazoda/basic-weapons/assets/42558699/734b17ea-a274-4709-ac73-1f9621a1a5d6)![image](https://github.com/Khazoda/basic-weapons/assets/42558699/29821ea2-5feb-4282-819a-f8d005b9dcc1)
## Two handed weapons (Spear, Quarterstaff)
![image](https://github.com/Khazoda/basic-weapons/assets/42558699/0ca9f70f-83b4-4591-8970-a373315cfe9c)![image](https://github.com/Khazoda/basic-weapons/assets/42558699/dbe17578-2777-4895-8809-78b45df3aaa3)

As you can see the two handed weapons have diagonal recipes, while the one handed ones have straight ones. Changing the dagger recipe to be diagonal messes up that design language. I'm not totally against it, as I realise it'd be more convenient, but if we can find a better solution that'd be ideal.

As an aside - I'm not totally happy with the dagger's role in the greater selection of weapon choices to be honest. Its only identity currently is that it's cheap and fast, but the damage is frankly too low while unenchanted to make it worth using, so I'm looking into changes to the dagger anyway, which will likely change its recipe. Thank you for posting the issue though, just know that I'm working on it 👍🏽If you have further suggestions on the topic feel free to open another issue.

**Comment by khazoda** [comment]
To alleviate this problem for now, I've implemented conditional recipe loading.
If farmer's delight is detected to be installed, the diagonal dagger recipe will be used, otherwise the normal recipe is used.

1.20.1: 53e25f9
1.21: 006073a
