### ISSUE TITLE
Hi! I was wondering how did you make the spears short in Gui, but in 3D model it's long.. 

### ISSUE THREAD

**Issue by makumaku1974** [khazoda/basicweapons-legacy#22]
I wanted to create swords that are short in slots but long when held. Did you perhaps used blockbench?

This is not for a custom or resourcepack weapons but I would try to make a mod about some swords.

**Comment by khazoda** [comment]
I can't guarantee that this is the best implementation, but this is how I did it using mixins:

- Create item model json files and textures for both gui and held variants (e.g. [diamond_quarterstaff_held.json](https://github.com/Khazoda/basic-weapons/blob/latest-stable/src/main/resources/assets/basicweapons/models/item/diamond_quarterstaff_held.json)
- Register the items as usual with the normal GUI item model.
- Make a mixin to load the held variant models so Minecraft can use them (e.g. [ModelLoaderMixin](https://github.com/Khazoda/basic-weapons/blob/latest-stable/src/client/java/com/seacroak/basicweapons/mixin/client/ModelLoaderMixin.java))
- Make a mixin to swap out the item model to the held variant when the item is being held (e.g. [ItemRendererMixin](https://github.com/Khazoda/basic-weapons/blob/latest-stable/src/client/java/com/seacroak/basicweapons/mixin/client/ItemRendererMixin.java))
- You will likely also need an accessor for the `models` field in ItemRenderer (e.g. [ItemRendererAccessor](https://github.com/Khazoda/basic-weapons/blob/latest-stable/src/client/java/com/seacroak/basicweapons/mixin/client/ItemRendererAccessor.java))

All of these mixins are clientside. Before 1.21 the code was a bit more succinct and readable, but the 1.21 port has made it a bit unwieldy. I'm unsure if it's the best approach, but it certainly works.

**Comment by makumaku1974** [comment]
So you made a 16x16 as the item, and basically it's extended for the handheld by player model? if im correct?

Tbh, I dont know anything about Java coding at this point. Currently using tutorials from youtube to try create my sword of course which is animated and has functionality. Which is really delightful to see some code of how you did it but I would get a nosebleed for reading too much.

**Comment by khazoda** [comment]
The large handheld textures are 32x32, the normal GUI textures are 16x16.

If you're new to modding I'd recommend reading the [Fabric Wiki](https://docs.fabricmc.net/develop/items/first-item),
and learning basic programming concepts.

Specifically for this mod my item registration is kind of weird, so I wouldn't follow that for your first mod, declare static initializers for your items like the wiki describes.

The technique you asked about uses mixins - I'd recommend getting more familiar with basic programming & java concepts before using them.
Good luck with your mod!
