### ISSUE TITLE
Hi i would like to request resourcepack support for Fresh Player Animations

### ISSUE THREAD

**Issue by BlackLightning-S** [khazoda/basicweapons-legacy#25]
This mod is really nice and i would like to play with it once 1.21 better combat comes out and it seems it is incompatible with this (https://www.curseforge.com/minecraft/texture-packs/fresh-player-animationsresourcepack) which is fantastic. Well better combat is more responsible for this but i thought maybe you might need to do some stuff forcompatibility as well. gonna do a similar one on better combat's github.

**Comment by khazoda** [comment]
hi, I love the fresh animations resource packs too - I believe that Basic Weapons will work without any changes on my part if Better Combat becomes compatible with the resource pack, as I just use Better Combat's JSON API.

**Comment by BlackLightning-S** [comment]
> hi, I love the fresh animations resource packs too - I believe that Basic Weapons will work without any changes on my part if Better Combat becomes compatible with the resource pack, as I just use Better Combat's JSON API.

Sorry i forgot to edit this but the owner of Better Combat stated that it was related to Player Animation Lib rather than Better Combat itself so i opened an issue there
