### ISSUE TITLE
Better Combat attack_animations folder now named player_animations

### ISSUE THREAD

**Issue by milkev** [khazoda/basicweapons-legacy#26]
**Minecraft version** - 1.21.1
**Mod loader** - neoforge 21.1.34
**Mod version** - 1.2.9
**I am using the latest version available** - as far as i know

**Describe the bug**
Better Combat changed the animation file name from `attack_animations` to `player_animations`, resulting in animations not working by default. [changelog of bettercombat](https://modrinth.com/mod/better-combat/version/2.0.0+1.21.1-fabric#:~:text=BREAKING!%20Asset%20directory%20for%20animations%20have%20been%20renamed%20from%20attack_animations%20to%20player_animations)

**To Reproduce**
1. Play game with the 1.21 release of better combat (just released)

**Expected behavior**
Attack animations working.

**Additional context**
Editting the .jar with winrar, i was able to fix the attack animations simply by renaming the folder to `player_animations`

**Comment by khazoda** [comment]
Thanks, this will be fixed ASAP.
I noticed you're using NeoForge on 1.21.1 with this mod - is that through Sinytra Connector?
I don't have a NeoForge release of the mod for 1.21.x which is why I'm asking.

**Comment by khazoda** [comment]
5d83c73 Fixed in release version 1.2.10+1.21.
(Up now on Modrinth, will be on CurseForge when they fix whatever's going on at the moment)

**Comment by milkev** [comment]
oh, yeah i am. i didnt even notice it was for fabric lol. love how flawlessly connector works.
