### ISSUE TITLE
Question: Is Fabric the only version that the mod supports since 1.21?

### ISSUE THREAD

**Issue by NovaViper** [khazoda/basicweapons-legacy#27]
I'm wondering if Basic Weapons is being supported for the Fabric modloader only. I see on Modrinth that it's the only version that's available on 1.21.x and not on either NeoForge or Quilt.

**Comment by khazoda** [comment]
Yes that's correct. I intend to bring Basic Weapons to NeoForge in the future but for now it's fabric only, sorry.
