### ISSUE TITLE
Why is there a space on every basic weapon tooltip?

### ISSUE THREAD

**Issue by Kloytz** [khazoda/basicweapons-legacy#30]
![image](https://github.com/user-attachments/assets/df1bc38a-7476-487f-adfc-4df51d079058)
![image](https://github.com/user-attachments/assets/8d2de9c4-b7f9-4ea5-81a3-a46aad863748)

**Comment by Kloytz** [comment]
nvm the space only appears on two handed weapons.

Weapons like the dagger and hammer appear as intended
![image](https://github.com/user-attachments/assets/a5ba8eb1-3adb-41b4-ba54-6f86d3e778a4)

**Comment by khazoda** [comment]
That's interesting..
- Which version of the mod are you using?
- Are you running the Better Combat mod as well?

**Comment by Kloytz** [comment]
Lastest version for 1.21.1
Yes im running the mod with better combat.

**Comment by khazoda** [comment]
Alright, I've checked my code on that version and I'm not modifying tooltips at all. As the empty line is right before 'Two Handed', which Better Combat adds (to my knowledge) it might be a bug with that mod instead.

I'd recommend creating an issue on their repo (if it doesn't exist already)
