### ISSUE TITLE
[1.21.1] Club & Quarterstaff Issues w/ Better Combat + Basic Weapons

### ISSUE THREAD

**Issue by Lockehartt** [khazoda/basicweapons-legacy#32]
Title gives the gist, but to be more specific:
- The Bronze Club just has the default, vanilla swing instead of the same animation set as the other clubs
- The Bronze Quarterstaff only uses the first Better Combat hit animation, doesn't go through the whole moveset

I was tinkering around with a personal pack and ran into this, so I tried the same trio of mods in a clean install of Simply Optimized (1.21-4.2) and still ran into this. Just wanted to let you know!

**Comment by khazoda** [comment]
Thank you for this bug report! I've confirmed it to be true and will work on fixing it asap :)

**Comment by khazoda** [comment]
Fixed the bug in 59d677f, will be in the next 1.21.x releases. Thanks again for the bug report!

**Comment by khazoda** [comment]
https://github.com/user-attachments/assets/19f08a04-eca2-4b67-bed9-eaacd5541153
