### ISSUE TITLE
Compatibility with Trimmable Tools

### ISSUE THREAD

**Issue by Tysos24** [khazoda/basicweapons-legacy#35]
Could you make a compatibility datapack or some such thing for the [Trimmable Tools](https://modrinth.com/datapack/trimmable-tools) mod? I don’t have any experience with modding or making datapacks, and, reading other issues, it looks like there are some rendering shenanigans as well.

**Comment by khazoda** [comment]
I've checked out Trimmable Tools' repo and I don't think I'll add integration sorry. The reasons:
- there doesn't seem to be any guide on adding support for new weapons
- new weapons would likely mean new overlay textures for every trim, which would take me too long

If it becomes easier in the future to add support I'll definitely reconsider it. Thanks for the suggestion :)

**Comment by Tysos24** [comment]
There’s kind of a guide somewhere in the issues, but I understand not wanting to make so many textures 👍
