### ISSUE TITLE
New Shield Type concept

### ISSUE THREAD

**Issue by pedro9006** [khazoda/basicweapons-legacy#9]
A new type of shield (which I'll just call a Basher for now)
 This shield is recommended to be used by people who prefer ranged combat.
 
![SmallShield](https://github.com/Khazoda/basic-weapons/assets/83221633/e9832727-6b04-4ddd-9db6-71f11e607466)

### Pros/Cons
 
 **+** When shielding, the player can move much quicker than when using a regular shield.
 **+** When the player unshields, they will unleash a bash attack, knocking away any entities in front of the player. (The Basher can be enchanted with Knockback to increase this effect)
 **+** Crafting a Basher is cheaper than crafting a regular shield.
 **-** The Basher has less durability than a regular shield.
 **-** When shielding, explosions get their damage reduced by 75%-80%, instead of being completely negated.
  **-** When shielding, melee attacks get their damage reduced by 80%-85%, instead of being completely negated.
 **-** After bashing an entity, the shield will go on cooldown. (albeit a shorter one than if it was hit by an axe)
 
![ShieldCrafting](https://github.com/Khazoda/basic-weapons/assets/83221633/60700f73-ef41-47cb-a5f3-3f7cc50d0202)

_**Any ideas and criticism on this concept would be greatly appreciated.**_

**Comment by khazoda** [comment]
This is a wonderful concept with a lot of thought put into it, and I'm a huge fan of the shield model too!

That being said - unfortunately I'm keeping Basic Weapons to just a few distinct melee weapons, not adding any ranged weapons or shields. If I work on a mod in the future that adds shields I will definitely contact you, as I think your idea is really cool and should be made by someone.
